### ISSUE TITLE
脚本的一些问题

### ISSUE THREAD

**Issue by mengguyi** [Morax-xyc/Bililiveauto#1]
我在使用大佬的脚本时，遇到如下问题：

![图片](https://user-images.githubusercontent.com/73788063/190417482-3b560a33-fd0c-4fa5-b4bd-48738ac6c45a.png)

1. 通过图片我认为是脚本获取时间戳时出现问题导致向`runbash.sh`传参时目录不存在

2. 另外脚本在下面处理时直接将时间转化成中文导致目录不存在(和第一条重复了，但是也说一下吧)

我使用的是raspbian，或许是系统的问题？

大佬用的什么系统测试的

时间转化成中文或许是我的系统语言是中文导致的？

**Comment by mengguyi** [comment]
这是我的env设置
```
# .env

#run
port=8081
rclonedir=SharePoint-MengGuyi:/影音/B站/直播
danmufc=/home/raspberrypi/DanmakuFactory/DanmakuFactory
workdir=/home/raspberrypi/Bililiveauto
bilifile=/mnt/Data/B站/blrec_work_space

#Telegram
TG_CHAT_ID=
TG_TOKEN=

#功能开关

#是否上传原始文件？true/false
uploadorigin=false

#是否删除本地文件？true/false
deletelocal=true
```

**Comment by Morax-xyc** [comment]
我一直使用的是debian，因为这个脚本写的时候没想过发出来，最开始没考虑做适配。所以后期调整的时候可能有一些地方出现了兼容性问题，请见谅。
我稍后再调试一下，看看是哪里的问题

**Comment by Morax-xyc** [comment]
应该不是语言问题，我设置的系统语言也是中文

**Comment by Morax-xyc** [comment]
啊…很抱歉
我忘记了录播姬可以自定义文件名，在js传参的地方写死了路径
我调整下…
